version: '3.9'
services:
  fuseki:
    build:
      context: .
      dockerfile: Dockerfile
    image: fuseki
    ports:
      - "3030:3030"
    volumes:
#      - ./_logs:/fuseki/run/logs
#      - ./_databases:/fuseki/run/databases
      - ./_data:/opt/run
#volumes:
